---
title: "QR codes"
format: html
---

This page was for generating the QR codes present for the ABRF 2026 talk. 

```{r}
library(qrcode)
```


# QC Dashboard

```{r}
code <- qr_code("https://umgccfcss.github.io/InstrumentQC/")

generate_svg(code, filename = "images/InstrumentQCQR.svg")
plot(code)
```

# QC How-To

```{r}
code <- qr_code("https://davidrach.github.io/InstrumentQC_Install/")

generate_svg(code, filename = "images/InstrumentQCHowToQR.svg")
plot(code)
```

# Luciernaga

```{r}
code <- qr_code("https://github.com/DavidRach/Luciernaga")

generate_svg(code, filename = "images/LuciernagaQR.svg")
plot(code)
```

# Coereba

```{r}
code <- qr_code("https://github.com/DavidRach/Coereba")

generate_svg(code, filename = "images/CoerebaQR.svg")
plot(code)
```

# CytometryInR

```{r}
code <- qr_code("https://umgcccfcsr.github.io/CytometryInR/Schedule.html")

generate_svg(code, filename = "images/CytometryInRWebsiteQR.svg")
plot(code)
```

# YouTube

```{r}
code <- qr_code("https://youtube.com/playlist?list=PL7tGF31b_cVqEkSLFvAX3kbtzUVpMe-VB&si=Xi1_x18JjzTaIMd_")

generate_svg(code, filename = "images/CytometryInRYouTubeQR.svg")
plot(code)
```

```{r}
print("Goodbye")
```



# YouTube

```{r}
code <- qr_code("https://github.com/DavidRach/")

generate_svg(code, filename = "images/DavidRachQR.svg")
plot(code)
```

# Discord

```{r}
code <- qr_code("https://discord.gg/ZmyPYUQr9Q/")

generate_svg(code, filename = "images/DiscordQR.svg")
```

# Reddit

```{r}
code <- qr_code("https:/reddit.com/r/flowcytometry/new")

generate_svg(code, filename = "images/RedditQR.svg")
```


# FITC Zombie Green Paper 

```{r}
code <- qr_code("https://www.jci.org/articles/view/139298/sd/1")

generate_svg(code, filename = "images/ZombieQR.svg")
```



```{r}
print("Goodbye")
```
